// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANfbvoK_rpywbansyJ9AwA2GWyrCb0DwY',
    appId: '1:705359044980:web:667ffa6ac6a56fa821cc21',
    messagingSenderId: '705359044980',
    projectId: 'chat-app-16f77',
    authDomain: 'chat-app-16f77.firebaseapp.com',
    storageBucket: 'chat-app-16f77.appspot.com',
    measurementId: 'G-VXT96KPG7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPhUXWFehenB_u6JPfWPp7k7svVyjf5KI',
    appId: '1:705359044980:android:231ce6871830453f21cc21',
    messagingSenderId: '705359044980',
    projectId: 'chat-app-16f77',
    storageBucket: 'chat-app-16f77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8XbgHi_L3wT0b0Zu-YL7DPD-3kzTF1k8',
    appId: '1:705359044980:ios:f866624279869d3821cc21',
    messagingSenderId: '705359044980',
    projectId: 'chat-app-16f77',
    storageBucket: 'chat-app-16f77.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8XbgHi_L3wT0b0Zu-YL7DPD-3kzTF1k8',
    appId: '1:705359044980:ios:f866624279869d3821cc21',
    messagingSenderId: '705359044980',
    projectId: 'chat-app-16f77',
    storageBucket: 'chat-app-16f77.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANfbvoK_rpywbansyJ9AwA2GWyrCb0DwY',
    appId: '1:705359044980:web:37220ecd5e1d032721cc21',
    messagingSenderId: '705359044980',
    projectId: 'chat-app-16f77',
    authDomain: 'chat-app-16f77.firebaseapp.com',
    storageBucket: 'chat-app-16f77.appspot.com',
    measurementId: 'G-1TFVGM721W',
  );
}
